apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinytinyrss.fullname" . }}
  labels:
    {{- include "tinytinyrss.labels" . | nindent 4 }}
type: Opaque
data:
  database_password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}